server {
    listen 80;
    location /videos/ {
        root /usr/share/nginx/html;
        autoindex on;
        autoindex_format json;
    }
    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
