# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: warehouse-mv3dt-app
description: NVIDIA Metropolis warehouse operations MV3DT app profile
type: application
version: 3.2.0
appVersion: "3.2.0"
keywords:
  - metropolis
  - warehouse
  - rtvi
  - mv3dt
maintainers:
  - name: NVIDIA
dependencies:
  - name: vios
    version: 3.2.0
    repository: "file://../../../services/vios"
    condition: vios.enabled
  - name: infra
    version: 3.2.0
    repository: "file://../../../services/infra"
    condition: infra.enabled
  - name: bp-configurator
    version: 3.2.0
    repository: "file://../../../services/bp-configurator"
    condition: bp-configurator.enabled
  - name: calibration-import
    version: 3.2.0
    repository: "file://../../../services/calibration-import"
    condition: calibration-import.enabled
  - name: rtvi
    version: 3.2.1
    repository: "file://../../../services/rtvi"
    condition: rtvi.enabled
  - name: analytics
    version: 3.2.0
    repository: "file://../../../services/analytics"
    condition: analytics.enabled
