# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.enabled (eq .Values.profileMode "standalone-mv3dt") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vss-rtvi-cv.fullname" . }}-warehouse-standalone-mv3dt-start
  labels:
    {{- include "vss-rtvi-cv.labels" . | nindent 4 }}
    vss-rtvi-cv.profileMode: standalone-mv3dt
data:
  ds-start-mv3dt.sh: |
{{ .Files.Get "files/warehouse-standalone-mv3dt/deepstream/init-scripts/ds-start-mv3dt.sh" | nindent 4 }}
{{- end }}
