# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.enabled (eq .Values.profileMode "standalone-mv3dt") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vss-rtvi-cv.fullname" . }}-warehouse-standalone-mv3dt-caminfo
  labels:
    {{- include "vss-rtvi-cv.labels" . | nindent 4 }}
    vss-rtvi-cv.profileMode: standalone-mv3dt
data:
{{- range $path, $_ := .Files.Glob "files/warehouse-standalone-mv3dt/calibration/camInfo/*" }}
{{- $base := base $path }}
  {{ $base }}: |
{{ $.Files.Get $path | nindent 4 }}
{{- end }}
{{- end }}
