{
  "downloads": [
    {
      "model": "nvidia/vss-warehouse/vss-warehouse-app-data:3.2.0",
      "org": "nvidia",
      "sourcePath": "vss-warehouse-app-data/models/sparse4d/ov/sparse4d_warehouse_v2.2.onnx",
      "destPath": "sparse4d/ov/sparse4d_warehouse_v2.2.onnx"
    },
    {
      "model": "nvidia/vss-warehouse/vss-warehouse-app-data:3.2.0",
      "org": "nvidia",
      "sourcePath": "vss-warehouse-app-data/models/sparse4d/ov/_ov_kmeans900_v2.2.npy",
      "destPath": "sparse4d/ov/_ov_kmeans900_v2.2.npy"
    }
  ]
}
