# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: calibration-import
description: NVIDIA Metropolis calibration import job
type: application
version: 3.2.0
appVersion: "1.0"
keywords:
  - metropolis
  - calibration
maintainers:
  - name: NVIDIA
