pubBrokerTopicStr:
  Camera: mosquitto:1883;/trck/Camera
  Camera_01: mosquitto:1883;/trck/Camera_01
  Camera_02: mosquitto:1883;/trck/Camera_02
  Camera_03: mosquitto:1883;/trck/Camera_03
subPeerBrokerTopicStrs:
  Camera:
  - mosquitto:1883;/trck/Camera_01
  - mosquitto:1883;/trck/Camera_02
  - mosquitto:1883;/trck/Camera_03
  Camera_01:
  - mosquitto:1883;/trck/Camera
  - mosquitto:1883;/trck/Camera_02
  - mosquitto:1883;/trck/Camera_03
  Camera_02:
  - mosquitto:1883;/trck/Camera
  - mosquitto:1883;/trck/Camera_01
  - mosquitto:1883;/trck/Camera_03
  Camera_03:
  - mosquitto:1883;/trck/Camera
  - mosquitto:1883;/trck/Camera_01
  - mosquitto:1883;/trck/Camera_02