{
  "downloads": [
    {
      "model": "nvidia/vss-warehouse/vss-warehouse-app-data:3.2.0",
      "org": "nvidia",
      "sourcePath": "vss-warehouse-app-data/models/mtmc/rtdetr_warehouse_v1.0.2.fp16.onnx",
      "destPath": "mtmc/rtdetr_warehouse_v1.0.2.fp16.onnx"
    }
  ]
}
