{
  "downloads": [
    {
      "model": "nvidia/tao/rtdetr_2d_warehouse:deployable_rn50_v1.0.2",
      "org": "nvidia",
      "sourcePath": "rtdetr_2d_warehouse_vdeployable_rn50_v1.0.2/rtdetr_warehouse_v1.0.2.fp16.onnx",
      "destPath": "rtdetr_warehouse_v1.0.2.fp16.onnx"
    },
    {
      "model": "nvidia/tao/${VISION_ENCODER_MODEL}:deployable_${VISION_ENCODER_VERSION}",
      "org": "nvidia",
      "sourcePath": "${VISION_ENCODER_MODEL}_vdeployable_${VISION_ENCODER_VERSION}/${VISION_ENCODER_MODEL}_${VISION_ENCODER_VERSION}.onnx",
      "destPath": "${VISION_ENCODER_MODEL}_${VISION_ENCODER_VERSION}.onnx"
    },
    {
      "model": "nvidia/tao/${VISION_ENCODER_MODEL}:deployable_${VISION_ENCODER_VERSION}",
      "org": "nvidia",
      "sourcePath": "${VISION_ENCODER_MODEL}_vdeployable_${VISION_ENCODER_VERSION}/${VISION_ENCODER_MODEL}_${VISION_ENCODER_VERSION}_weights.bin",
      "destPath": "${VISION_ENCODER_MODEL}_${VISION_ENCODER_VERSION}_weights.bin",
      "compatSymlink": "siglip2_${VISION_ENCODER_VERSION}_weights.bin"
    },
    {
      "model": "nvidia/tao/${VISION_ENCODER_MODEL}:deployable_${VISION_ENCODER_VERSION}",
      "org": "nvidia",
      "sourcePath": "${VISION_ENCODER_MODEL}_vdeployable_${VISION_ENCODER_VERSION}/${VISION_ENCODER_MODEL}_${VISION_ENCODER_VERSION}_tokenizer",
      "destPath": "${VISION_ENCODER_MODEL}_${VISION_ENCODER_VERSION}_tokenizer"
    }
  ]
}
