# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PREBUILT=$(TOP)/$(PREBUILT_DIR)
TARGET := $(PREBUILT)libnvwebrtc_streamer.so

SRCS := PeerConnectionManager.cpp \
		PeerConnection.cpp \
		WebrtcCallbacks.cpp \
		peerconnection_manager_apis.cpp \
		screencapturer.cpp \
		nvgstvideocapturer.cpp \
		nvgstaudiocapturer.cpp \
		nvgstudpvideocapturer.cpp \
		nvgstudpaudiocapturer.cpp \
		webrtcDataChannel.cpp \
		WebrtcStreamStats.cpp \
		hlsmanager.cpp \
		sensordatamanager.cpp \
		rtspvideocapturer.cpp \
		mkvclient.cpp \
		nvgstvideosource.cpp

CPP = c++
OBJS := $(SRCS:.cpp=.o)

CPPFLAGS += -I $(TOP)/src/framework/webrtc_streamer/inc/webrtc_headers/src/third_party/abseil-cpp \
			-I $(TOP)/src/framework/media/video_source/core
# Sub-make may not inherit root CPPFLAGS in all CI images; keep WebRTC deprecations non-fatal.
CPPFLAGS += -Wno-error=deprecated
# Pull libwebrtc.a into this DSO: PeerConnection.cpp calls
# webrtc::CreateBuiltinAudioDecoderFactory(), which in the prebuilt is
# GLOBAL HIDDEN in builtin_audio_decoder_factory.o. If we do not link webrtc
# here, the .so keeps UND for that symbol; at launch_vst link GNU ld errors
# "hidden symbol ... in libwebrtc.a is referenced by DSO".
LDFLAGS := -rdynamic -shared -L$(PREBUILT) -Wl,--start-group -ljsoncpp -lnvvideo_source -lnvoverlays -lwebrtc -Wl,--end-group -pthread -ldl

all: $(TARGET)

%.o: %.cpp %.d
	@echo "Compiling: $<"
	$(CXX) $(DEPFLAGS) $(CPPFLAGS) -c $< -o $@

$(TARGET): $(OBJS)
	@echo "Linking: $@"
	$(CXX) -o $@ $(OBJS) $(CPPFLAGS) $(LDFLAGS)

include $(TOP)/Makefile.dep

clean:
	$(AT)rm -rf $(TARGET) $(OBJS)
