# This file is provided under Apache-2.0 License.

pipeline.workers: 1
pipeline.ordered: true
pipeline.ecs_compatibility: disabled
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
api.http.host: "0.0.0.0"