# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  kibana-init-container-lvs:
    build:
      context: $VSS_APPS_DIR/developer-profiles/dev-profile-lvs
      dockerfile: $VSS_APPS_DIR/developer-profiles/dev-profile-lvs/Dockerfiles/kibana-dashboard.Dockerfile
    profiles: ["kibana-init-container-lvs"]
    container_name: vss-kibana-init
    command: bash /opt/mdx/init-scripts/kibana-import-dashboard.sh
    restart: on-failure
    depends_on:
      kibana:
        condition: service_healthy

  nvstreamer-lvs:
    image: nvcr.io/nvidia/vss-core/vss-vios-nvstreamer:${NVSTREAMER_IMAGE_TAG}
    user: "0:0"
    profiles: ["nvstreamer-lvs"]
    entrypoint: ["/bin/bash", "-c", "if [ \"$$NVSTREAMER_INSTALL_ADDITIONAL_PACKAGES\" = \"true\" ]; then /home/vst/vst_release/tools/user_additional_install.sh; fi && exec /home/vst/vst_release/launch_vst"]
    environment:
      - NVSTREAMER_INSTALL_ADDITIONAL_PACKAGES=${NVSTREAMER_INSTALL_ADDITIONAL_PACKAGES}
      - ADAPTOR=streamer
      - HTTP_PORT=${NVSTREAMER_HTTP_PORT}
    ports:
      - ${NVSTREAMER_HTTP_HOST_PORT:-31000}:${NVSTREAMER_HTTP_PORT:-31000}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 2
    container_name: vss-vios-nvstreamer-lvs
    networks:
      default:
        aliases:
          - vss-vios-nvstreamer
    volumes:
      - $VSS_APPS_DIR/developer-profiles/dev-profile-lvs/nvstreamer/configs/vst-config.json:/home/vst/vst_release/configs/vst_config.json
      - $VSS_APPS_DIR/developer-profiles/dev-profile-lvs/nvstreamer/configs/vst-storage.json:/home/vst/vst_release/configs/vst_storage.json
      - $VSS_DATA_DIR/videos/dev-profile-lvs:/home/vst/vst_release/streamer_videos
      - $VSS_DATA_DIR/data_log/nvstreamer/vst_data:/home/vst/vst_release/vst_data
      - $VSS_APPS_DIR/services/vios/scripts/user_additional_install.sh:/home/vst/vst_release/tools/user_additional_install.sh
    depends_on:
      broker-health-check:
        condition: service_completed_successfully